// Code generated by sed. DO NOT EDIT
package doublearray

import (
	"github.com/ajiyoshi-vg/hairetsu/node"
	"github.com/ajiyoshi-vg/hairetsu/word"
)

type Bytes struct{}

func (Bytes) ExactMatchSearch(da Nodes, cs []byte) (node.Index, error) {
	var parent node.Index
	target, err := da.At(parent)
	if err != nil {
		return 0, err
	}
	for _, c := range cs {
		child := target.GetChild(word.Code(c))
		target, err = da.At(child)
		if err != nil {
			return 0, err
		}
		if !target.IsChildOf(parent) {
			return 0, ErrNotAChild
		}
		parent = child
	}
	if !target.IsTerminal() {
		return 0, ErrNotATerminal
	}
	data, err := da.At(target.GetChild(word.EOS))
	if err != nil {
		return 0, err
	}
	return data.GetOffset(), nil
}

func (Bytes) CommonPrefixSearch(da Nodes, cs []byte) ([]node.Index, error) {
	var ret []node.Index
	var parent node.Index
	target, err := da.At(parent)
	if err != nil {
		return ret, nil
	}

	for _, c := range cs {
		child := target.GetChild(word.Code(c))
		target, err = da.At(child)
		if err != nil {
			return ret, nil
		}
		if !target.IsChildOf(parent) {
			return ret, nil
		}
		parent = child
		if target.IsTerminal() {
			data, err := da.At(target.GetChild(word.EOS))
			if err != nil {
				return ret, nil
			}
			ret = append(ret, data.GetOffset())
		}
	}
	return ret, nil
}
