// Code generated by sed. DO NOT EDIT
package doublearray

import (
	"github.com/ajiyoshi-vg/hairetsu/bytes"
	"github.com/ajiyoshi-vg/hairetsu/node"
	"github.com/ajiyoshi-vg/hairetsu/word"
)

type BytesDict bytes.Dict

func (s BytesDict) ExactMatchSearch(da Nodes, cs []byte) (node.Index, error) {
	target, parent, err := InitialTarget(da)
	if err != nil {
		return 0, err
	}

	for _, c := range cs {
		code := bytes.Dict(s).Code(c)
		target, parent, err = NextTarget(da, code, target, parent)
		if err != nil {
			return 0, err
		}
	}

	if !target.IsTerminal() {
		return 0, ErrNotATerminal
	}
	data, err := da.At(target.GetChild(word.EOS))
	if err != nil {
		return 0, err
	}
	return data.GetOffset(), nil
}

func (s BytesDict) CommonPrefixSearch(da Nodes, cs []byte) ([]node.Index, error) {
	var ret []node.Index
	target, parent, err := InitialTarget(da)
	if err != nil {
		return nil, err
	}

	for _, c := range cs {
		code := bytes.Dict(s).Code(c)
		target, parent, err = NextTarget(da, code, target, parent)
		if err != nil {
			return ret, nil
		}

		if target.IsTerminal() {
			data, err := da.At(target.GetChild(word.EOS))
			if err != nil {
				return ret, nil
			}
			ret = append(ret, data.GetOffset())
		}
	}
	return ret, nil
}
